service: the-four-words-bot

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}



functions:
  post:
    handler: handler.handle_message
    events:
      - http:
          path: handle_message_telegram
          method: post
          cors: true